#!/usr/bin/env python3
"""Source of truth for the cheat-sheet content. Run to regenerate data.js."""
import json

def ex(code, note="", out=""):
    return {"code": code, "note": note, "out": out}

SECTIONS = [
    {"id": "orient", "num": "01", "title": "Getting oriented",
     "lede": "Where you are, what the prompt is telling you, and how to get help without leaving the terminal."},
    {"id": "nav", "num": "02", "title": "File navigation",
     "lede": "Moving around the filesystem, making and removing things, and finding files on a shared cluster."},
    {"id": "view", "num": "03", "title": "Core utilities",
     "lede": "Look inside files without opening an editor: cat, head, tail, wc, and the small tools you chain them with."},
    {"id": "redirect", "num": "04", "title": "Redirection & pipes",
     "lede": "Every command has three streams. Redirection decides where they come from and where they go."},
    {"id": "quote", "num": "05", "title": "Quoting rules",
     "lede": "Quotes decide what the shell expands and where it splits words. Most mysterious bugs start here."},
]

CARDS = [
    # ---------------- ORIENT ----------------
    {"id": "prompt", "sec": "orient", "cmd": "prompt", "title": "Read the prompt",
     "summary": "The prompt tells you who you are, which machine you are on, and your current directory. On a cluster, the hostname matters: login nodes are shared and are not for heavy computation.",
     "syntax": "[user@host directory]$",
     "ex": [
         ex("hostname", "Which node am I on? login01 = shared login node; c0423 = compute node.", "login01.cluster.edu"),
         ex("whoami", "Your username, which is also the owner of your $HOME.", "ada"),
         ex("echo $HOME $SCRATCH", "Your home and scratch locations. $SCRATCH is site-specific; check your cluster docs.", "/home/ada /scratch/ada"),
     ],
     "tips": ["`~` at the end of the prompt means you are in your home directory.",
              "A `>` prompt instead of `$` means the shell is waiting for you to finish something, usually an unclosed quote. Press Ctrl-C to bail out."],
     "warn": ["Do not run long or memory-heavy jobs on a login node. Request a compute node with `srun --pty bash` or submit with `sbatch` (Slurm)."]},

    {"id": "help", "sec": "orient", "cmd": "man / --help", "title": "Get help",
     "summary": "Every standard command documents itself. `--help` gives a quick summary; `man` gives the full manual page.",
     "syntax": "man COMMAND   |   COMMAND --help   |   type COMMAND",
     "ex": [
         ex("head --help", "Short usage summary for GNU tools."),
         ex("man wc", "Full manual. Space = next page, b = back, /word = search, q = quit."),
         ex("type cd ls", "Is it a builtin, an alias, or a program on disk?", "cd is a shell builtin\nls is aliased to `ls --color=auto'"),
         ex("module avail samtools", "On HPC, software is often hidden behind environment modules."),
     ],
     "tips": ["`help cd` works for shell builtins that have no man page."],
     "warn": []},

    {"id": "keys", "sec": "orient", "cmd": "shortcuts", "title": "Keyboard shortcuts",
     "summary": "These save more time than any alias. Tab completion also prevents typos in long filenames.",
     "syntax": "Tab · Ctrl-C · Ctrl-D · Ctrl-R · Ctrl-A / Ctrl-E · ↑ ↓",
     "ex": [
         ex("# Tab        complete a file or command name (press twice to list options)\n# Ctrl-C     cancel the running command / abandon the current line\n# Ctrl-D     end of input; on an empty prompt it logs you out\n# Ctrl-R     search backwards through history\n# Ctrl-A / E jump to start / end of line\n# Ctrl-L     clear the screen\n# Up / Down  previous / next command", "Reference, not something to run."),
         ex("history | tail -n 20", "Your last 20 commands."),
         ex("!!", "Re-run the previous command. `sudo !!` is the classic, but you rarely have sudo on a cluster."),
     ],
     "tips": [],
     "warn": ["Ctrl-S freezes terminal output in many terminals. If your screen stops responding, press Ctrl-Q."]},

    # ---------------- NAV ----------------
    {"id": "pwd", "sec": "nav", "cmd": "pwd", "title": "Print working directory",
     "summary": "Shows the absolute path of the directory you are in. Run it whenever you are unsure where a relative path will point.",
     "syntax": "pwd",
     "ex": [ex("pwd", "", "/scratch/ada/project/fastq")],
     "tips": [], "warn": []},

    {"id": "ls", "sec": "nav", "cmd": "ls", "title": "List directory contents",
     "summary": "Lists files. Flags combine: `-lh` is the same as `-l -h`.",
     "syntax": "ls [-l] [-a] [-h] [-t] [-r] [PATH...]",
     "ex": [
         ex("ls -lh", "Long listing with human-readable sizes (K, M, G).", "-rw-r--r-- 1 ada lab 1.2G Oct  2 09:14 S01_R1.fastq.gz"),
         ex("ls -la", "Include hidden dotfiles such as .bashrc."),
         ex("ls -ltr", "Sort by time, oldest first, so the newest file ends up next to your prompt."),
         ex("ls *.vcf.gz", "Glob: the shell expands the pattern before ls ever runs."),
         ex("ls -d */", "Directories only."),
     ],
     "tips": ["Read permissions as owner / group / others: `rw-r--r--` means you can write, everyone else can only read."],
     "warn": ["`ls` on a directory with millions of files can hang the shared filesystem. Use `ls -f | head` or `find . -maxdepth 1 | head`."]},

    {"id": "cd", "sec": "nav", "cmd": "cd", "title": "Change directory",
     "summary": "Moves you to another directory. With no argument, it takes you home.",
     "syntax": "cd [PATH]",
     "ex": [
         ex("cd /scratch/$USER/project", "Absolute path: starts with /, works from anywhere."),
         ex("cd data/raw", "Relative path: resolved from where you are now."),
         ex("cd ..", "Up one level. `cd ../..` goes up two."),
         ex("cd ~", "Home. Plain `cd` does the same."),
         ex("cd -", "Back to the previous directory, like a TV remote's 'last channel'."),
         ex("cd \"My Data\"", "Quote names that contain spaces."),
     ],
     "tips": ["`.` is the current directory, `..` is the parent, `~` is your home, `/` is the filesystem root."],
     "warn": []},

    {"id": "paths", "sec": "nav", "cmd": "paths", "title": "Absolute vs relative paths",
     "summary": "An absolute path starts at `/` and means the same thing everywhere. A relative path depends on your current directory, which is why scripts that work interactively can fail inside a batch job.",
     "syntax": "/abs/path   rel/path   ./file   ../sibling   ~/file",
     "ex": [
         ex("realpath reads.fq", "Turn a relative path into an absolute one.", "/scratch/ada/project/reads.fq"),
         ex("cd \"$SLURM_SUBMIT_DIR\"", "Inside a Slurm job script: start where you ran sbatch, so relative paths behave."),
         ex("./run_qc.sh", "Run a script in the current directory. The ./ is required because . is not on $PATH."),
     ],
     "tips": [], "warn": ["`~` is not expanded inside quotes: `\"~/data\"` is a literal tilde. Use `\"$HOME/data\"`."]},

    {"id": "mkdir", "sec": "nav", "cmd": "mkdir", "title": "Make directories",
     "summary": "Creates directories. `-p` creates parent directories as needed and does not complain if the directory already exists.",
     "syntax": "mkdir [-p] DIR...",
     "ex": [
         ex("mkdir results", ""),
         ex("mkdir -p results/qc/fastqc logs", "Nested path plus a second directory in one call."),
         ex("mkdir -p analysis/{raw,trimmed,aligned}", "Brace expansion creates three sibling directories."),
     ],
     "tips": [], "warn": []},

    {"id": "cp", "sec": "nav", "cmd": "cp", "title": "Copy files",
     "summary": "Copies files. Directories need `-r`. With several sources, the last argument must be a directory.",
     "syntax": "cp [-r] [-i] [-v] SOURCE... DEST",
     "ex": [
         ex("cp config.yaml config.yaml.bak", "Quick backup before editing."),
         ex("cp -r ref/ /scratch/$USER/ref/", "Copy a directory tree."),
         ex("cp -i *.vcf archive/", "-i asks before overwriting anything."),
         ex("rsync -avh --progress data/ /scratch/$USER/data/", "For large transfers, rsync resumes and shows progress."),
     ],
     "tips": [], "warn": ["`cp` overwrites the destination silently unless you use `-i` or `-n`."]},

    {"id": "mv", "sec": "nav", "cmd": "mv", "title": "Move or rename",
     "summary": "Renaming and moving are the same operation. Moving within one filesystem is instant regardless of size.",
     "syntax": "mv [-i] [-n] SOURCE... DEST",
     "ex": [
         ex("mv sample1.fq S01_R1.fq", "Rename."),
         ex("mv *.log logs/", "Move many files into a directory."),
         ex("mv -n new.txt old.txt", "-n never overwrites an existing file."),
     ],
     "tips": [], "warn": ["`mv a.txt b.txt` replaces b.txt without asking if it exists."]},

    {"id": "rm", "sec": "nav", "cmd": "rm", "title": "Remove files",
     "summary": "Deletes files permanently. There is no recycle bin on a cluster, and scratch is usually not backed up.",
     "syntax": "rm [-i] [-r] [-f] PATH...",
     "ex": [
         ex("rm tmp.txt", ""),
         ex("rm -i *.bam", "Confirm each deletion."),
         ex("rm -r old_run/", "Remove a directory and everything in it."),
         ex("ls *.tmp && rm *.tmp", "Preview what a glob matches before deleting it."),
         ex("rmdir empty_dir", "Removes only empty directories: a safe default."),
     ],
     "tips": [],
     "warn": ["`rm -rf $DIR/` with an empty `$DIR` becomes `rm -rf /`. Quote and guard: `rm -rf \"${DIR:?not set}\"/`.",
              "A stray space is fatal: `rm -rf ./ data` deletes the current directory, not ./data."]},

    {"id": "find", "sec": "nav", "cmd": "find", "title": "Find files",
     "summary": "Recursively searches a directory tree by name, type, size, or age. Quote the pattern so find, not the shell, does the matching.",
     "syntax": "find PATH [-name 'PATTERN'] [-type f|d] [-size +N] [-mtime -N]",
     "ex": [
         ex("find . -name '*.fastq.gz'", "Every gzipped FASTQ below here."),
         ex("find /scratch/$USER -type f -size +10G", "Large files that are eating your quota."),
         ex("find . -name '*.log' -mtime -1", "Logs modified in the last 24 hours."),
         ex("find . -maxdepth 1 -type d", "Immediate subdirectories only."),
         ex("find . -name '*.tmp' -print", "Always run with -print first; only then swap it for -delete."),
     ],
     "tips": [], "warn": ["Unquoted `find . -name *.txt` breaks when the current directory already contains a .txt file, because the shell expands it first."]},

    {"id": "du", "sec": "nav", "cmd": "du / df / quota", "title": "Disk usage",
     "summary": "Clusters enforce quotas. When writes start failing, these show where your space went.",
     "syntax": "du -sh PATH   |   df -h PATH   |   quota -s",
     "ex": [
         ex("du -sh *", "Size of each item in the current directory."),
         ex("du -sh * | sort -h", "Same, sorted smallest to largest."),
         ex("df -h $HOME", "Free space on the filesystem holding your home."),
         ex("quota -s", "Your quota on many systems. Some sites use `myquota`, `lfs quota`, or a custom command."),
     ],
     "tips": [], "warn": []},

    {"id": "ln", "sec": "nav", "cmd": "ln -s", "title": "Symbolic links",
     "summary": "A shortcut that points at another path. Useful for linking shared reference genomes into your project without copying them.",
     "syntax": "ln -s TARGET LINK_NAME",
     "ex": [
         ex("ln -s /shared/refs/Pinus_taeda_v2.fa ref.fa", "ref.fa now points to the shared genome."),
         ex("ls -l ref.fa", "", "ref.fa -> /shared/refs/Pinus_taeda_v2.fa"),
     ],
     "tips": ["The argument order matches `cp`: what exists first, then the new name."], "warn": []},

    # ---------------- VIEW ----------------
    {"id": "cat", "sec": "view", "cmd": "cat", "title": "Concatenate & print",
     "summary": "Prints whole files to the screen, or joins several files into one stream. Best for small files.",
     "syntax": "cat [-n] [-A] FILE...",
     "ex": [
         ex("cat samples.txt", "Print a short file."),
         ex("cat -n samples.txt", "Number every line."),
         ex("cat part1.fq part2.fq > combined.fq", "Join files. Order is preserved."),
         ex("cat -A sheet.csv | head", "Show hidden characters: `^M$` at line ends means Windows line endings."),
     ],
     "tips": ["Gzipped FASTQ files can be concatenated directly: `cat a.fq.gz b.fq.gz > ab.fq.gz` produces a valid gzip file."],
     "warn": ["Running `cat` on a 50 GB file floods your terminal. Use `head` or `less` instead.",
              "`cat` with no filename waits for keyboard input. Press Ctrl-D (end) or Ctrl-C (cancel)."]},

    {"id": "head", "sec": "view", "cmd": "head", "title": "First lines",
     "summary": "Shows the start of a file, 10 lines by default. Ideal for peeking at headers and file formats.",
     "syntax": "head [-n N] [-c BYTES] FILE...",
     "ex": [
         ex("head data.csv", "First 10 lines."),
         ex("head -n 4 reads.fastq", "One FASTQ record is exactly 4 lines."),
         ex("head -n -1 data.csv", "GNU only: everything except the last line."),
         ex("zcat reads.fastq.gz | head -n 8", "Peek inside a gzipped file without decompressing it to disk."),
         ex("head -n 1 *.csv", "Several files: head prints a ==> name <== banner for each."),
     ],
     "tips": [], "warn": ["`gzip: stdout: Broken pipe` after `zcat | head` is harmless: head simply stopped reading early."]},

    {"id": "tail", "sec": "view", "cmd": "tail", "title": "Last lines",
     "summary": "Shows the end of a file. `-f` keeps following it as it grows, which is how you watch a running job's log.",
     "syntax": "tail [-n N] [-n +K] [-f] FILE",
     "ex": [
         ex("tail -n 20 slurm-123456.out", "Last 20 lines of a job log."),
         ex("tail -f slurm-123456.out", "Live view. Ctrl-C stops watching; it does not stop the job."),
         ex("tail -n +2 data.csv", "Start at line 2, i.e. drop the header."),
         ex("head -n 200 data.csv | tail -n 1", "Print exactly line 200."),
     ],
     "tips": [], "warn": []},

    {"id": "less", "sec": "view", "cmd": "less", "title": "Page through a file",
     "summary": "Opens a file one screen at a time without loading it all into memory. Safe on huge files.",
     "syntax": "less [-S] [-N] FILE",
     "ex": [
         ex("less -S variants.vcf", "-S turns off line wrapping; use ← → to scroll wide VCF rows."),
         ex("zless reads.fastq.gz", "Page through a gzipped file."),
         ex("# inside less:\n#   Space / b   page down / up\n#   g / G       start / end\n#   /pattern    search forward, n = next match\n#   q           quit", "Keys to remember."),
     ],
     "tips": [], "warn": []},

    {"id": "wc", "sec": "view", "cmd": "wc", "title": "Count lines, words, bytes",
     "summary": "Counts lines (`-l`), words (`-w`), and bytes (`-c`). Strictly, `-l` counts newline characters.",
     "syntax": "wc [-l] [-w] [-c] FILE...",
     "ex": [
         ex("wc -l samples.txt", "Filename is printed after the count.", "96 samples.txt"),
         ex("wc -l < samples.txt", "Read from stdin instead: you get just the number, handy in scripts.", "96"),
         ex("echo $(( $(zcat reads.fq.gz | wc -l) / 4 ))", "Number of reads in a FASTQ: lines divided by 4."),
         ex("grep -vc '^#' variants.vcf", "Count variant rows, skipping header lines (grep -c counts matches)."),
         ex("wc -l *.txt", "Several files get a 'total' line at the end."),
     ],
     "tips": [], "warn": ["If the last line has no trailing newline, `wc -l` reports one fewer line than you expect."]},

    {"id": "sort", "sec": "view", "cmd": "sort / uniq", "title": "Sort and deduplicate",
     "summary": "`sort` orders lines; `uniq` collapses adjacent duplicates. Because uniq only looks at neighbors, you almost always sort first.",
     "syntax": "sort [-n] [-h] [-r] [-k N] [-t SEP] [-u] FILE   |   uniq [-c] [-d]",
     "ex": [
         ex("sort -k2,2n coords.tsv", "Sort numerically on column 2 only."),
         ex("sort -t, -k3,3 data.csv", "Comma-separated: sort on the third field."),
         ex("cut -f1 calls.tsv | sort | uniq -c | sort -rn", "Frequency table of column 1, most common first."),
         ex("sort -u ids.txt", "Sort and drop duplicates in one step."),
     ],
     "tips": [], "warn": ["Without `-n`, sort is alphabetical: 10 comes before 9."]},

    {"id": "cut", "sec": "view", "cmd": "cut", "title": "Extract columns",
     "summary": "Pulls out fields from delimited text. The default delimiter is Tab.",
     "syntax": "cut -f LIST [-d DELIM] FILE",
     "ex": [
         ex("cut -f1,2 variants.tsv", "Columns 1 and 2 of a tab-separated file."),
         ex("cut -d, -f3- data.csv", "Comma-separated, column 3 to the end."),
         ex("grep -v '^##' variants.vcf | cut -f1-5 | head", "Peek at CHROM POS ID REF ALT."),
     ],
     "tips": [], "warn": ["cut cannot handle quoted CSV fields that contain commas. Use `csvcut` or R/Python for real CSV."]},

    {"id": "grep", "sec": "view", "cmd": "grep", "title": "Search text",
     "summary": "Prints lines that match a pattern. Quote the pattern in single quotes so the shell leaves it alone.",
     "syntax": "grep [-i] [-v] [-c] [-n] [-w] [-E] [-r] 'PATTERN' FILE...",
     "ex": [
         ex("grep 'ERROR' slurm-*.out", "Which job logs mention an error?"),
         ex("grep -c '^>' contigs.fa", "Count sequences in a FASTA (lines starting with >)."),
         ex("grep -v '^#' variants.vcf | head", "-v inverts: skip header lines."),
         ex("grep -n -i 'oom' job.log", "Case-insensitive, with line numbers."),
         ex("grep -E 'S0[1-5]_' samples.txt", "Extended regular expressions."),
         ex("zgrep -c 'PASS' calls.vcf.gz", "Search inside a gzipped file."),
     ],
     "tips": [], "warn": ["`grep '>' file` is fine. `grep > file` (no quotes) truncates file and grep waits for input."]},

    {"id": "zcat", "sec": "view", "cmd": "zcat / gzip", "title": "Compressed files",
     "summary": "Most sequencing data arrives gzipped. The z-tools let you read it without unpacking to disk.",
     "syntax": "zcat FILE.gz   |   gzip [-k] FILE   |   gunzip FILE.gz",
     "ex": [
         ex("zcat reads.fq.gz | head -n 4", "First FASTQ record."),
         ex("gzip -k results.tsv", "-k keeps the original file."),
         ex("gunzip -t reads.fq.gz && echo OK", "Test archive integrity after a transfer."),
         ex("tar -xzf archive.tar.gz", "Extract a .tar.gz (x = extract, z = gzip, f = file)."),
     ],
     "tips": [], "warn": []},

    # ---------------- REDIRECT ----------------
    {"id": "streams", "sec": "redirect", "cmd": "0 1 2", "title": "The three standard streams",
     "summary": "Every process starts with three file descriptors: 0 = stdin (input, normally the keyboard), 1 = stdout (normal output), 2 = stderr (errors and warnings). Both 1 and 2 normally go to your terminal, which is why they look identical until you redirect one.",
     "syntax": "0 stdin   1 stdout   2 stderr",
     "ex": [
         ex("ls real.txt missing.txt > out.txt", "The listing goes to out.txt; the error still appears on screen because it is stderr.", "ls: cannot access 'missing.txt': No such file or directory"),
     ],
     "tips": ["Slurm writes both streams to `slurm-JOBID.out` by default. Use `#SBATCH -o` and `#SBATCH -e` to split them."], "warn": []},

    {"id": "gt", "sec": "redirect", "cmd": ">", "title": "Write stdout to a file",
     "summary": "Sends stdout into a file, creating it if needed and truncating it to zero length first if it exists.",
     "syntax": "command > FILE",
     "ex": [
         ex("ls *.bam > bam_list.txt", ""),
         ex("set -o noclobber", "Protect yourself: now `>` refuses to overwrite existing files. Use `>|` to force."),
     ],
     "tips": [], "warn": ["The file is truncated before the command runs. `sort data.txt > data.txt` leaves you with an empty file."]},

    {"id": "gtgt", "sec": "redirect", "cmd": ">>", "title": "Append stdout",
     "summary": "Adds to the end of a file instead of replacing it.",
     "syntax": "command >> FILE",
     "ex": [
         ex("echo \"$(date) started $SAMPLE\" >> run.log", "Build up a log across many commands."),
         ex("for f in *.csv; do tail -n +2 \"$f\" >> merged.csv; done", "Append every file minus its header."),
     ],
     "tips": [], "warn": ["Rerunning an appending script doubles the output. Clear the file first with `> merged.csv` if needed."]},

    {"id": "lt", "sec": "redirect", "cmd": "<", "title": "Read stdin from a file",
     "summary": "Feeds a file into a command's standard input. The command sees data but not a filename.",
     "syntax": "command < FILE",
     "ex": [
         ex("wc -l < samples.txt", "Prints only the count, with no filename.", "96"),
         ex("while read -r id; do echo \"processing $id\"; done < samples.txt", "Loop over lines of a file."),
     ],
     "tips": [], "warn": []},

    {"id": "err", "sec": "redirect", "cmd": "2> / 2>&1 / &>", "title": "Redirect errors",
     "summary": "Put a file descriptor number before the operator to redirect that stream. `2>&1` means 'make stderr go wherever stdout currently goes'.",
     "syntax": "cmd 2> err.txt   |   cmd > all.txt 2>&1   |   cmd &> all.txt",
     "ex": [
         ex("bwa mem ref.fa r1.fq r2.fq > aln.sam 2> bwa.log", "Data to one file, messages to another: the standard bioinformatics pattern."),
         ex("./pipeline.sh > run.log 2>&1", "Both streams into one file. Order matters: file first, then 2>&1."),
         ex("./pipeline.sh &> run.log", "Bash shorthand for the line above."),
         ex("find / -name '*.fa' 2> /dev/null", "Discard the permission-denied noise."),
     ],
     "tips": [],
     "warn": ["`cmd 2>&1 > file` is not the same as `cmd > file 2>&1`. Redirections run left to right; in the first form stderr copies stdout while it still points at the terminal."]},

    {"id": "pipe", "sec": "redirect", "cmd": "|", "title": "Pipes",
     "summary": "Connects one command's stdout to the next command's stdin. Nothing touches the disk in between.",
     "syntax": "cmd1 | cmd2 | cmd3",
     "ex": [
         ex("zcat reads.fq.gz | head -n 400000 | gzip > subset.fq.gz", "Take the first 100,000 reads."),
         ex("grep -v '^#' calls.vcf | cut -f1 | sort | uniq -c", "Variants per chromosome."),
         ex("cmd 2>&1 | less", "Pipes only carry stdout. Merge stderr first if you want to page through errors too."),
         ex("set -o pipefail", "In scripts: make a pipeline fail if any stage fails, not just the last one."),
     ],
     "tips": [], "warn": []},

    {"id": "tee", "sec": "redirect", "cmd": "tee", "title": "Split output: screen and file",
     "summary": "Copies stdin to a file and to stdout, so you can watch output and save it at the same time.",
     "syntax": "cmd | tee [-a] FILE",
     "ex": [
         ex("./qc.sh 2>&1 | tee qc.log", "Watch it live and keep a log."),
         ex("./qc.sh | tee -a qc.log", "-a appends instead of overwriting."),
     ],
     "tips": [], "warn": []},

    {"id": "devnull", "sec": "redirect", "cmd": "/dev/null", "title": "The bit bucket",
     "summary": "A special file that discards anything written to it and is always empty when read.",
     "syntax": "cmd > /dev/null 2>&1",
     "ex": [
         ex("command -v samtools > /dev/null || echo 'load the samtools module first'", "Check that a tool exists, without printing its path."),
         ex("grep -q 'PASS' calls.vcf && echo found", "grep -q is a cleaner way to stay silent."),
     ],
     "tips": [], "warn": ["Silencing stderr also hides real errors. Do it only when you know what you are throwing away."]},

    {"id": "heredoc", "sec": "redirect", "cmd": "<< EOF", "title": "Here-documents",
     "summary": "Feeds a block of inline text to a command's stdin. Quoting the delimiter (`'EOF'`) turns off variable expansion inside the block.",
     "syntax": "cmd << EOF ... EOF   |   cmd << 'EOF' ... EOF",
     "ex": [
         ex("cat > samples.txt << EOF\nS01\nS02\nS03\nEOF", "Write a small file without opening an editor."),
         ex("cat > job.sh << 'EOF'\n#!/bin/bash\n#SBATCH -t 01:00:00\necho \"running on $HOSTNAME\"\nEOF", "Quoted delimiter: $HOSTNAME is written literally and expanded later, on the compute node."),
         ex("grep -c x <<< \"$SEQ\"", "Here-string: feed a single variable as stdin."),
     ],
     "tips": [], "warn": ["The closing EOF must be alone on its line with no leading spaces (unless you use `<<-` with tabs)."]},

    {"id": "procsub", "sec": "redirect", "cmd": "<( )", "title": "Process substitution",
     "summary": "Treats a command's output as if it were a file. Great for tools that demand filenames.",
     "syntax": "cmd <(other_cmd) <(other_cmd)",
     "ex": [
         ex("diff <(sort a.txt) <(sort b.txt)", "Compare two files ignoring order."),
         ex("comm -12 <(sort ids_a.txt) <(sort ids_b.txt)", "IDs present in both lists."),
         ex("paste <(cut -f1 a.tsv) <(cut -f3 b.tsv)", "Glue columns from two files side by side."),
     ],
     "tips": [], "warn": ["Bash only. It fails in `sh` with `syntax error near unexpected token '('`."]},

    # ---------------- QUOTE ----------------
    {"id": "single", "sec": "quote", "cmd": "'...'", "title": "Single quotes: fully literal",
     "summary": "Everything between single quotes is taken exactly as typed. No variables, no globs, no backslash escapes. You cannot put a single quote inside single quotes.",
     "syntax": "'literal text'",
     "ex": [
         ex("echo 'Cost: $5 * 3'", "", "Cost: $5 * 3"),
         ex("grep -E '^chr[0-9]+\\s' file.bed", "The safe default for regular expressions."),
         ex("awk '{print $1}' data.tsv", "Single quotes protect awk's own $1 from the shell."),
         ex("echo 'It'\\''s done'", "To include a quote: close, add an escaped quote, reopen.", "It's done"),
     ],
     "tips": [], "warn": []},

    {"id": "double", "sec": "quote", "cmd": "\"...\"", "title": "Double quotes: expand, but do not split",
     "summary": "Variables (`$VAR`) and command substitution (`$(...)`) still expand, but the result stays one word, and globs are not expanded. Inside, a backslash only escapes `$`, backtick, `\"`, and `\\`.",
     "syntax": "\"text with $VAR and $(cmd)\"",
     "ex": [
         ex("FILE=\"my reads.fq\"\nwc -l \"$FILE\"", "Without quotes, wc would look for two files: my and reads.fq."),
         ex("echo \"Home is $HOME, today is $(date +%F)\"", "", "Home is /home/ada, today is 2026-10-05"),
         ex("echo \"Price: \\$5\"", "Escape a literal dollar.", "Price: $5"),
     ],
     "tips": ["Rule of thumb: always double-quote variable expansions, `\"$var\"`, unless you specifically want splitting."], "warn": []},

    {"id": "backslash", "sec": "quote", "cmd": "\\", "title": "Backslash escapes",
     "summary": "Outside quotes, a backslash makes the next single character literal. At the end of a line it continues the command onto the next line.",
     "syntax": "\\CHAR   |   long command \\",
     "ex": [
         ex("ls My\\ Data/", "Escape a space (Tab completion does this for you)."),
         ex("sbatch --job-name=qc \\\n       --time=02:00:00 \\\n       --mem=8G run.sh", "Split a long command over lines."),
     ],
     "tips": [], "warn": ["A space after the trailing backslash breaks line continuation, and the error is almost invisible."]},

    {"id": "vars", "sec": "quote", "cmd": "$VAR ${VAR}", "title": "Variables",
     "summary": "Assign with no spaces around `=`. Use braces when the name is followed by characters that could be part of a name.",
     "syntax": "NAME=value   \"$NAME\"   \"${NAME}_suffix\"",
     "ex": [
         ex("SAMPLE=S01\necho \"${SAMPLE}_R1.fq\"", "Without braces, bash looks for a variable named SAMPLE_R1.", "S01_R1.fq"),
         ex("OUT=${OUT:-results}", "Default value if OUT is unset or empty."),
         ex("f=reads.fastq.gz\necho \"${f%.fastq.gz}\"", "Strip a suffix: a clean way to build output names.", "reads"),
         ex("export THREADS=8", "export makes the variable visible to programs you launch."),
     ],
     "tips": [], "warn": ["`NAME = value` (with spaces) runs a command called NAME. Bash replies `NAME: command not found`."]},

    {"id": "cmdsub", "sec": "quote", "cmd": "$( )", "title": "Command substitution",
     "summary": "Runs a command and pastes its output in place. Prefer `$(...)` over old-style backticks because it nests and reads clearly.",
     "syntax": "\"$(command)\"",
     "ex": [
         ex("N=$(wc -l < samples.txt)\necho \"There are $N samples\"", "", "There are 96 samples"),
         ex("mkdir \"run_$(date +%Y%m%d)\"", "Date-stamped output directory."),
         ex("echo \"Job $SLURM_JOB_ID on $(hostname)\"", ""),
     ],
     "tips": [], "warn": []},

    {"id": "glob", "sec": "quote", "cmd": "* ? [ ]", "title": "Globs (wildcards)",
     "summary": "Unquoted `*`, `?`, and `[...]` are expanded by the shell into matching filenames before the command runs. Quoting turns them back into literal characters.",
     "syntax": "*  any string   ?  one char   [abc]  one of   {a,b}  brace list",
     "ex": [
         ex("ls S0?_R1.fq.gz", "S01 to S09, but not S10."),
         ex("ls *_R[12].fq.gz", "Both read pairs."),
         ex("echo *.fasta", "If nothing matches, bash passes the literal text *.fasta.", "*.fasta"),
         ex("echo '*.fasta'", "Quoted: never expanded.", "*.fasta"),
         ex("for f in *.fq.gz; do echo \"$f\"; done", "Loop over files the safe way. Never parse `ls` output."),
     ],
     "tips": ["`{a,b}` brace expansion is not a glob: it always expands, whether or not files exist."], "warn": []},

    {"id": "spaces", "sec": "quote", "cmd": "spaces", "title": "Spaces in filenames",
     "summary": "The shell splits words on spaces. A name like `Field Notes.txt` becomes two arguments unless you quote or escape it. Easiest fix: avoid spaces in names you create.",
     "syntax": "\"Field Notes.txt\"   'Field Notes.txt'   Field\\ Notes.txt",
     "ex": [
         ex("cat \"Field Notes.txt\"", ""),
         ex("for f in *.txt; do mv \"$f\" \"${f// /_}\"; done", "Replace spaces with underscores in every .txt filename."),
         ex("find . -name '*.txt' -print0 | xargs -0 wc -l", "-print0 and -0 keep odd filenames intact through a pipe."),
     ],
     "tips": [], "warn": []},

    {"id": "remote", "sec": "quote", "cmd": "nested", "title": "Quoting across ssh & sbatch --wrap",
     "summary": "When a command string is handed to another shell, it is parsed twice: once locally, once remotely. Choose the outer quote type based on where you want variables to expand.",
     "syntax": "ssh host 'cmd $REMOTE_VAR'   |   sbatch --wrap \"cmd $LOCAL_VAR\"",
     "ex": [
         ex("ssh cluster 'echo $HOSTNAME'", "Single quotes: expanded on the remote machine.", "login01"),
         ex("ssh cluster \"echo $HOSTNAME\"", "Double quotes: expanded locally before sending.", "my-laptop"),
         ex("sbatch --wrap=\"gzip -k '$PWD/big file.tsv'\"", "Outer double quotes expand $PWD now; inner single quotes protect the space later."),
     ],
     "tips": [], "warn": []},
]

ERRORS = [
    {"msg": "command not found", "full": "-bash: samtools: command not found",
     "cause": "The program is not on your $PATH. On a cluster this usually means its module is not loaded. It can also be a typo, or a script in the current directory run without ./",
     "fix": "module avail samtools\nmodule load samtools\n./myscript.sh        # not just myscript.sh",
     "tags": "path module typo"},
    {"msg": "No such file or directory", "full": "head: cannot open 'Reads.fq' for reading: No such file or directory",
     "cause": "Wrong path, wrong case (Linux is case-sensitive), or a relative path resolved from a different directory than you thought. Also appears when a glob matches nothing and is passed through literally.",
     "fix": "pwd\nls -l\nrealpath reads.fq",
     "tags": "path case glob"},
    {"msg": "Permission denied", "full": "-bash: ./run.sh: Permission denied",
     "cause": "Either the script lacks the execute bit, or you are trying to write into a directory you do not own (for example a shared reference folder or another user's home).",
     "fix": "chmod +x run.sh\nbash run.sh          # or run it via bash directly\nls -ld /shared/refs  # check directory permissions",
     "tags": "chmod execute write"},
    {"msg": "Is a directory", "full": "cat: results: Is a directory",
     "cause": "You gave a directory where a file was expected.",
     "fix": "ls results/\ncat results/summary.txt",
     "tags": "directory cat"},
    {"msg": "-r not specified; omitting directory", "full": "cp: -r not specified; omitting directory 'ref'",
     "cause": "cp copies files only, unless told to recurse into directories.",
     "fix": "cp -r ref/ backup_ref/",
     "tags": "cp directory recursive"},
    {"msg": "> prompt that will not go away", "full": ">\n>\n>",
     "cause": "The shell is waiting for you to finish an unclosed quote, bracket, or here-document. It is not frozen.",
     "fix": "# Press Ctrl-C to cancel the line, then retype it with balanced quotes\necho \"done\"",
     "tags": "quote ps2 continuation"},
    {"msg": "unexpected EOF while looking for matching", "full": "line 12: unexpected EOF while looking for matching `\"'",
     "cause": "A script has an unclosed quote somewhere above the line reported. Bash only notices at the end of the file.",
     "fix": "bash -n script.sh     # syntax check without running\ngrep -n '\"' script.sh   # find the odd one out",
     "tags": "quote script syntax"},
    {"msg": "ambiguous redirect", "full": "-bash: $OUT: ambiguous redirect",
     "cause": "The redirection target is an unquoted variable that is empty or contains spaces, so it does not expand to exactly one filename.",
     "fix": "echo \"[$OUT]\"         # inspect it\ncmd > \"$OUT\"",
     "tags": "redirect variable quote"},
    {"msg": "[: too many arguments", "full": "-bash: [: too many arguments",
     "cause": "An unquoted variable inside a test contained spaces and was split into several words.",
     "fix": "if [ \"$name\" = \"S01 rep1\" ]; then echo match; fi\n# or use [[ ]] which does not split\nif [[ $name == \"S01 rep1\" ]]; then echo match; fi",
     "tags": "test quote variable"},
    {"msg": "File is empty after sort/cat/grep", "full": "$ sort data.txt > data.txt\n$ wc -l data.txt\n0 data.txt",
     "cause": "The shell truncates the output file before the command starts reading the same file. The data is gone.",
     "fix": "sort data.txt > data.sorted.txt && mv data.sorted.txt data.txt\nsort -o data.txt data.txt     # sort can do it safely itself",
     "tags": "redirect truncate overwrite"},
    {"msg": "bad interpreter: /bin/bash^M", "full": "-bash: ./run.sh: /bin/bash^M: bad interpreter: No such file or directory",
     "cause": "The script was edited on Windows and has CRLF line endings. The invisible \\r becomes part of every line.",
     "fix": "cat -A run.sh | head -n 2   # shows ^M$ at line ends\nsed -i 's/\\r$//' run.sh       # or: dos2unix run.sh",
     "tags": "windows crlf line endings"},
    {"msg": "event not found", "full": "-bash: !nice: event not found",
     "cause": "In interactive bash, `!` inside double quotes triggers history expansion.",
     "fix": "echo 'Job done!nice'     # single quotes\nset +H                   # or turn history expansion off",
     "tags": "quote history bang"},
    {"msg": "NAME: command not found (on assignment)", "full": "-bash: THREADS: command not found",
     "cause": "Spaces around `=` turn a variable assignment into a command named THREADS with arguments `=` and `8`.",
     "fix": "THREADS=8",
     "tags": "variable assignment spaces"},
    {"msg": "Argument list too long", "full": "-bash: /bin/rm: Argument list too long",
     "cause": "A glob such as `*.tmp` expanded to more filenames than the kernel allows in a single command.",
     "fix": "find . -name '*.tmp' -delete\n# or process in batches\nfind . -name '*.fq' -print0 | xargs -0 gzip",
     "tags": "glob xargs find"},
    {"msg": "Disk quota exceeded", "full": "cp: error writing 'big.bam': Disk quota exceeded",
     "cause": "You hit your storage or file-count limit, usually in $HOME, which tends to be small on clusters.",
     "fix": "quota -s\ndu -sh ~/* | sort -h | tail\nmv ~/big_run /scratch/$USER/",
     "tags": "quota storage hpc"},
    {"msg": "Killed", "full": "Killed",
     "cause": "The process was terminated, often for using too much memory on a login node, or (inside a job) for exceeding the memory you requested. Slurm logs show `oom-kill` or `OUT_OF_MEMORY`.",
     "fix": "srun --mem=16G --time=01:00:00 --pty bash   # interactive compute node\nsacct -j JOBID --format=JobID,State,MaxRSS,ReqMem",
     "tags": "memory oom slurm login node"},
    {"msg": "Terminal hangs after cat or grep", "full": "$ cat\n_",
     "cause": "You ran a command that reads stdin without giving it a file, so it is waiting for you to type. Common after a missing filename, or after `grep pattern > file` with no input file.",
     "fix": "# Ctrl-D to send end-of-input, or Ctrl-C to cancel\ngrep 'pattern' input.txt > hits.txt",
     "tags": "stdin hang cat"},
    {"msg": "gzip: stdout: Broken pipe", "full": "gzip: stdout: Broken pipe",
     "cause": "Harmless. `head` or `less` stopped reading early, so the upstream command was told to stop.",
     "fix": "zcat reads.fq.gz 2>/dev/null | head",
     "tags": "pipe gzip head"},
    {"msg": "syntax error near unexpected token `('", "full": "sh: syntax error near unexpected token `('",
     "cause": "You used a bash-only feature, such as `<( )` or arrays, in a script run by `sh`, or you have an unquoted parenthesis in a filename.",
     "fix": "bash script.sh            # not: sh script.sh\n#!/bin/bash                # first line of the script\nls \"sample (copy).txt\"",
     "tags": "bash sh shebang"},
]

# Compact quick-reference rows for the printable sheet
QUICK = [
    ("Navigate", [("pwd", "where am I"), ("ls -lh", "list with sizes"), ("cd DIR", "go to DIR"), ("cd ..", "up one"), ("cd -", "previous dir"), ("cd", "home"), ("realpath F", "absolute path")]),
    ("Manage", [("mkdir -p a/b", "make nested dirs"), ("cp -r SRC DST", "copy (dirs need -r)"), ("mv OLD NEW", "move / rename"), ("rm -i F", "delete, ask first"), ("ln -s T L", "symlink"), ("find . -name '*.x'", "find by name"), ("du -sh *", "sizes here")]),
    ("Inspect", [("cat F", "print file"), ("head -n N F", "first N lines"), ("tail -n N F", "last N lines"), ("tail -n +2 F", "skip header"), ("tail -f LOG", "follow log"), ("less -S F", "page, no wrap"), ("wc -l F", "count lines")]),
    ("Filter", [("grep 'p' F", "matching lines"), ("grep -v 'p'", "non-matching"), ("grep -c 'p'", "count matches"), ("cut -f1,3", "columns (tab)"), ("sort -k2,2n", "sort numeric col 2"), ("uniq -c", "count adjacent dupes"), ("zcat F.gz", "read gzip")]),
    ("Redirect", [("> F", "stdout to F (overwrite)"), (">> F", "stdout append"), ("< F", "stdin from F"), ("2> F", "stderr to F"), ("> F 2>&1", "both to F"), ("&> F", "both (bash)"), ("a | b", "stdout of a into b"), ("| tee F", "screen + file"), ("2> /dev/null", "discard errors")]),
    ("Quote", [("'...'", "literal, nothing expands"), ("\"...\"", "expand $ but keep one word"), ("\\x", "escape one char"), ("\"$VAR\"", "always quote vars"), ("\"${V}_x\"", "braces before text"), ("\"$(cmd)\"", "insert output"), ("'*.txt'", "stop glob expansion")]),
    ("Keys", [("Tab", "complete"), ("Ctrl-C", "cancel"), ("Ctrl-D", "end input / logout"), ("Ctrl-R", "search history"), ("Ctrl-A / E", "line start / end"), ("q", "quit less / man")]),
]

REDIR = [
    {"op": "cmd", "label": "no redirection", "stdin": "keyboard", "stdout": "terminal", "stderr": "terminal",
     "note": "By default both output streams land on your screen, interleaved."},
    {"op": "cmd > out.txt", "label": ">", "stdin": "keyboard", "stdout": "out.txt", "stderr": "terminal",
     "note": "stdout goes to the file (truncated first). Errors still show on screen."},
    {"op": "cmd >> out.txt", "label": ">>", "stdin": "keyboard", "stdout": "out.txt (append)", "stderr": "terminal",
     "note": "Same as >, but adds to the end of the file."},
    {"op": "cmd < in.txt", "label": "<", "stdin": "in.txt", "stdout": "terminal", "stderr": "terminal",
     "note": "The command reads its input from the file instead of the keyboard."},
    {"op": "cmd 2> err.txt", "label": "2>", "stdin": "keyboard", "stdout": "terminal", "stderr": "err.txt",
     "note": "Only stderr (fd 2) is captured. Normal output still prints."},
    {"op": "cmd > out.txt 2> err.txt", "label": "> 2>", "stdin": "keyboard", "stdout": "out.txt", "stderr": "err.txt",
     "note": "Split data from diagnostics: the classic aligner pattern."},
    {"op": "cmd > all.txt 2>&1", "label": "> 2>&1", "stdin": "keyboard", "stdout": "all.txt", "stderr": "all.txt",
     "note": "First point stdout at the file, then make stderr a copy of stdout. Both end up in the file."},
    {"op": "cmd 2>&1 > all.txt", "label": "2>&1 > (wrong order)", "stdin": "keyboard", "stdout": "all.txt", "stderr": "terminal",
     "note": "Trap: stderr copied stdout while stdout was still the terminal. Only stdout reaches the file.", "trap": True},
    {"op": "cmd &> all.txt", "label": "&>", "stdin": "keyboard", "stdout": "all.txt", "stderr": "all.txt",
     "note": "Bash shorthand for > all.txt 2>&1."},
    {"op": "cmd | next", "label": "|", "stdin": "keyboard", "stdout": "next (stdin)", "stderr": "terminal",
     "note": "Only stdout flows down the pipe. Errors bypass it and print to the screen."},
    {"op": "cmd 2>&1 | next", "label": "2>&1 |", "stdin": "keyboard", "stdout": "next (stdin)", "stderr": "next (stdin)",
     "note": "Merge stderr into stdout, then pipe both."},
    {"op": "cmd 2> /dev/null", "label": "2> /dev/null", "stdin": "keyboard", "stdout": "terminal", "stderr": "/dev/null (discarded)",
     "note": "Throw errors away. Use sparingly."},
    {"op": "cmd | tee log.txt", "label": "| tee", "stdin": "keyboard", "stdout": "terminal + log.txt", "stderr": "terminal",
     "note": "tee duplicates stdout to the screen and a file."},
]

data = {"sections": SECTIONS, "cards": CARDS, "errors": ERRORS,
        "quick": [{"group": g, "rows": [{"c": c, "d": d} for c, d in rows]} for g, rows in QUICK],
        "redir": REDIR}

with open("data.js", "w") as fh:
    fh.write("window.SHEET = ")
    json.dump(data, fh, ensure_ascii=False, indent=1)
    fh.write(";\n")
print(len(CARDS), "cards,", len(ERRORS), "errors")
