project:
  type: website
  output-dir: docs

website:
  title: "Anoob Prakash"
  description: "Personal website for Anoob Prakash"
  image: img/illustrated_AP.jpg
  favicon: img/illustrated_AP.jpg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/AP_logo2.png
    
    # your sub-pages
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Notebook"
        href: notebook/index.qmd
      - text: "Gallery"
        href: gallery/index.qmd
      - text: "News"
        href: news/news.qmd
      - text: "CV"
        href: cv/cv.qmd
           
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/anoob-prakash/
      # - icon: google
      #   href: https://scholar.google.com/citations?hl=en&user=jIOSRMkAAAAJ
      # - icon: github
      #   href: https://github.com/anoobvinu07
      # - icon: envelope
      #   aria-label: email
      #   href: "mailto:anoobvinu@gmail.com"
      
      

        
  # person-workspace
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: overlay
  page-footer: 
    left:
        - icon: github
          href: https://github.com/anoobvinu07
        - icon: mortarboard
          href: https://scholar.google.com/citations?hl=en&user=jIOSRMkAAAAJ
        - icon: envelope
          href: mailto:anoobvinu@gmail.com

    right:
        - icon: building
          href: https://ag.purdue.edu/directory/prakas89
        - text: Purdue
          href: https://www.purdue.edu
        - text: HTIRC
          href: https://htirc.org/      
          
    center: |
      
      © <span id="year"></span> · Anoob Prakash
      <script>
        document.getElementById("year").textContent = new Date().getFullYear();
      </script>
  

 
format:
  html:
    fontsize: 1.4em
    theme: 
      light: style2.scss
      dark:  style2-dark.scss

      
      # - style2-dark.scss
    toc: true
    toc-depth: 4
    toc-title: ""
    footnotes-hover: true
    highlight-style: tango